export {
  createFastScatterPlot,
  createFastScatterPlot as createScatterPlot,
} from './createScatterPlot.js';
export { createDefaultScatterBindings } from './defaultScatterBindings.js';
export type {
  DefaultScatterBindingsOptions,
  ScatterEasterEggBindingOptions,
} from './defaultScatterBindings.js';
export type {
  FastScatterPlotCommands,
  FastScatterPlotCommands as ScatterPlotCommands,
} from './scatterCommands.js';
export type {
  FastScatterActivePlotChangeEvent,
  FastScatterActivePlotChangeEvent as ScatterActivePlotChangeEvent,
  FastScatterBrushEvent,
  FastScatterBrushEvent as ScatterBrushEvent,
  FastScatterContextEvent,
  FastScatterContextEvent as ScatterContextEvent,
  FastScatterCursorChangeEvent,
  FastScatterCursorChangeEvent as ScatterCursorChangeEvent,
  FastScatterEngineEventName,
  FastScatterEngineEventName as ScatterEngineEventName,
  FastScatterEngineEvents,
  FastScatterEngineEvents as ScatterEngineEvents,
  FastScatterHeatmapBinSizeAdjustRequestEvent,
  FastScatterHeatmapBinSizeAdjustRequestEvent as ScatterHeatmapBinSizeAdjustRequestEvent,
  FastScatterOverlayChangeEvent,
  FastScatterOverlayChangeEvent as ScatterOverlayChangeEvent,
  FastScatterPointSizeAdjustRequestEvent,
  FastScatterPointSizeAdjustRequestEvent as ScatterPointSizeAdjustRequestEvent,
  FastScatterRenderStateEvent,
  FastScatterRenderStateEvent as ScatterRenderStateEvent,
  FastScatterViewportChangeEvent,
  FastScatterViewportChangeEvent as ScatterViewportChangeEvent,
  FastScatterViewportUndoRequestEvent,
  FastScatterViewportUndoRequestEvent as ScatterViewportUndoRequestEvent,
} from './scatterEvents.js';
export type {
  FastScatterCommittedSelectionOverlay,
  FastScatterCommittedSelectionOverlay as ScatterCommittedSelectionOverlay,
  FastScatterColorRuleBrushOverlay,
  FastScatterColorRuleBrushOverlay as ScatterColorRuleBrushOverlay,
  FastScatterCssPoint,
  FastScatterCssPoint as ScatterCssPoint,
  FastScatterCssRect,
  FastScatterCssRect as ScatterCssRect,
  FastScatterCursorTooltipOverlay,
  FastScatterCursorTooltipOverlay as ScatterCursorTooltipOverlay,
  FastScatterHoverGuideOverlay,
  FastScatterHoverGuideOverlay as ScatterHoverGuideOverlay,
  FastScatterLassoOverlay,
  FastScatterLassoOverlay as ScatterLassoOverlay,
  FastScatterMeasurementGuideOverlay,
  FastScatterMeasurementGuideOverlay as ScatterMeasurementGuideOverlay,
  FastScatterNavigatorOverlay,
  FastScatterNavigatorOverlay as ScatterNavigatorOverlay,
  FastScatterOutOfRangeMarkersOverlay,
  FastScatterOutOfRangeMarkersOverlay as ScatterOutOfRangeMarkersOverlay,
  FastScatterOverlayBase,
  FastScatterOverlayBase as ScatterOverlayBase,
  FastScatterOverlayDescriptor,
  FastScatterOverlayDescriptor as ScatterOverlayDescriptor,
  FastScatterOverlayKind,
  FastScatterOverlayKind as ScatterOverlayKind,
  FastScatterPointMarkerOverlay,
  FastScatterPointMarkerOverlay as ScatterPointMarkerOverlay,
  FastScatterRectangleSelectionOverlay,
  FastScatterRectangleSelectionOverlay as ScatterRectangleSelectionOverlay,
  FastScatterRectangleZoomOverlay,
  FastScatterRectangleZoomOverlay as ScatterRectangleZoomOverlay,
} from './scatterOverlays.js';
export type {
  FastScatterCursorState,
  FastScatterCursorState as ScatterCursorState,
  FastScatterRenderSnapshot,
  FastScatterRenderSnapshot as ScatterRenderSnapshot,
  FastScatterRenderState,
  FastScatterRenderState as ScatterRenderState,
  FastScatterStateSnapshot,
  FastScatterStateSnapshot as ScatterStateSnapshot,
} from './scatterState.js';
export type {
  FastScatterBinding,
  FastScatterBinding as ScatterBinding,
  FastScatterPlotInstance,
  FastScatterPlotInstance as ScatterPlotInstance,
  FastScatterPlotOptions,
  FastScatterPlotOptions as ScatterPlotOptions,
  FastScatterRendererFactory,
  FastScatterRendererFactory as ScatterRendererFactory,
  FastScatterRendererLike,
  FastScatterRendererLike as ScatterRendererLike,
} from './types.js';
